### ISSUE TITLE
Problem with TV resolutions

### ISSUE THREAD

**Issue by kydex** [zoicware/OverrideEDID#1]
I have a monitor (3440x1440@160) and TV (3840x2160@144Hz) connected to my PC. This script removes all TV resolutions and leave only 1080p.
I tried running the script only when the monitor is on, and also when both the monitor and TV are on.
But it didn't help. I need to leave active TV resolutions 3840x2160@144Hz and 3840x2160@120Hz. How can I do this?

**Comment by zoicware** [comment]
> I have a monitor (3440x1440@160) and TV (3840x2160@144Hz) connected to my PC. This script removes all TV resolutions and leave only 1080p. I tried running the script only when the monitor is on, and also when both the monitor and TV are on. But it didn't help. I need to leave active TV resolutions 3840x2160@144Hz and 3840x2160@120Hz. How can I do this?

the newest Nvidia drivers fixed this bug so its no longer needed if you are still getting the issue youll have to do it manually since this was made for 1080p monitors
